### ISSUE TITLE
How do I resize image correctly ?

### ISSUE THREAD

**Issue by winston432** [JingWangTW/dark-theme-editor#8]
Hi,

In my markdown file, I have following image embeded.

```![alt text](image.png)```

Could you advise the correct way of resizing the image while I am using dark-theme-editor ?

best regards,
winston

**Comment by JingWangTW** [comment]
Hello,

Sorry for the late update. Unfortunately, there is no easy way to resize images in markdown currently. The style file fixes the width of the image to 100%. Apparently, unless you write the inline style, there is no way to overwrite this rule. This will be fixed in the next release. Thanks for your understanding.

**Comment by winston432** [comment]
thank you for advise.
